Add --cover-erase param to test execution commands
py34 test execution would fail due to a UnicodeDecodeError exception being
raised by the coverage package from a previous python versions run.

Per the nose docs, the `--cover-erase` option will "erase previously collected
coverage statistics before run"

https://nose.readthedocs.io/en/latest/plugins/cover.html#cmdoption-cover-erase

No Travis impact is expected, as no coverage statistics would exist in that run context.

Full traceback:

```python
py34-pymongo-pyexecjs run-test: commands[0] | nosetests -x -s --with-coverage --cover-package=mongomock --show-skipped
Traceback (most recent call last):
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/coverage/data.py", line 293, in read_file
    self.read_fileobj(f)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/coverage/data.py", line 271, in read_fileobj
    data = self._read_raw_data(file_obj)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/coverage/data.py", line 311, in _read_raw_data
    go_away = file_obj.read(len(cls._GO_AWAY))
  File "/root/.pyenv/versions/3.4.10/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 98: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mongomock/.tox/py34-pymongo-pyexecjs/bin/nosetests", line 10, in <module>
    sys.exit(run_exit())
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "/root/.pyenv/versions/3.4.10/lib/python3.4/unittest/main.py", line 92, in __init__
    self.parseArgs(argv)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/nose/core.py", line 145, in parseArgs
    self.config.configure(argv, doc=self.usage())
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/nose/config.py", line 346, in configure
    self.plugins.configure(options, self)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/nose/plugins/manager.py", line 284, in configure
    cfg(options, config)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/nose/plugins/manager.py", line 99, in __call__
    return self.call(*arg, **kw)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/nose/plugins/manager.py", line 167, in simple
    result = meth(*arg, **kw)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/nose/plugins/cover.py", line 155, in configure
    self.coverInstance.load()
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/coverage/control.py", line 677, in load
    self.data_files.read(self.data)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/coverage/data.py", line 653, in read
    data.read_file(self.filename)
  File "/mongomock/.tox/py34-pymongo-pyexecjs/lib/python3.4/site-packages/coverage/data.py", line 297, in read_file
    filename, exc.__class__.__name__, exc,
coverage.misc.CoverageException: Couldn't read data from '/mongomock/.coverage': UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 98: ordinal not in range(128)
```